# Generated by Django 2.2.7 on 2019-11-12 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='track',
            new_name='file',
        ),
    ]
