# Generated by Django 2.2.7 on 2019-11-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_userlist'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='playlist',
            order_with_respect_to='creatorId',
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
