# Generated by Django 2.2.7 on 2019-11-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0007_userslists'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersLists',
        ),
    ]
