# Generated by Django 2.2.7 on 2019-11-22 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0008_delete_userslists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='creatorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='playlist.User'),
        ),
    ]
